- name: Install curl
  become: true
  ansible.builtin.apt:
      name: curl
      state: present

- name: Isntall wget
  become: true
  ansible.builtin.apt:
      name: wget
      state: present

- name: Install git
  become: true
  ansible.builtin.apt:
    name: git
    state: present

- name: Install jq
  become: true
  ansible.builtin.apt:
    name: jq
    state: present

- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install passlib
  become: true
  pip:
    name: passlib
    state: present