- name: NOpassword for bocal
  become: true
  lineinfile:
    path: /etc/sudoers
    line: 'bocal ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'

- name: Change user bocal password
  become: true
  user:
    name: bocal
    password: "{{ newpassword|password_hash('sha512') }}"
